version: '3.8'

services:
    frontend:
      build: ./example-frontend 
      #ports:
      #  - 5000:5000
    backend:
      build: ./example-backend
      #ports:
      #  - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_PASSWORD=example
        - POSTGRES_HOST=db
        - REQUEST_ORIGIN=http://localhost
        - FRONT_URL=http://localhost
    redis:
      image: redis

    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      volumes:
        - type: bind 
          source: ./database
          target: /var/lib/postgresql/data

    nginx-proxy:
      image: nginx:1.19-alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
    database:
